name: CI

on:
    push:
        branches:
            - '1.x'
    pull_request:

jobs:
    cs-fixer:
        name: "PHP-CS-Fixer"
        runs-on: ubuntu-latest
        steps:
            - name: Check out code into the workspace
              uses: actions/checkout@v3
            - name: Setup PHP 8.2
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"
                  tools: php-cs-fixer
            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Install libraries via Composer
              run: composer update --prefer-dist --no-interaction --no-dev
            - name: Run php-cs-fixer
              run: php-cs-fixer fix --dry-run --verbose

    phpstan:
        name: "PHPStan"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ['8.1', '8.2']
                include:
                    - php-version: '8.1'
                      composer-flags: '--prefer-lowest'
        steps:
            - name: Check out code into the workspace
              uses: actions/checkout@v3
            - name: Setup PHP ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: phpstan
            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ matrix.prefer }}-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-${{ matrix.prefer }}-
            - name: Install libraries via Composer
              run: composer update ${{ matrix.composer-flags }} --prefer-dist --no-interaction --no-dev
            - name: Run phpstan
              run: phpstan analyze --verbose

    box-validate:
        name: "Validate Box config"
        runs-on: ubuntu-latest
        steps:
            - name: Check out code into the workspace
              uses: actions/checkout@v3
            - name: Setup PHP 8.2
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"
                  tools: humbug/box:^4.5
            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Install libraries via Composer
              run: composer update --prefer-dist --no-interaction --no-dev
            - name: Run box validate
              run: box validate
