name: CI

on:
    push:
        branches:
            - 2.x
    pull_request:

jobs:
    latest:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php:
                    - '8.1'
                    - '8.2'
                    - '8.3'

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Execute tests
              run: make phpcs
