name: CI

on:
    push:
        branches:
            - 1.x
    pull_request:

jobs:
    latest:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.4'
                    - '8.0'
                    - '8.1'

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer:v2
                  coverage: none

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Update dependencies for PHP 8
              if: matrix.php >= '8.0'
              run: composer update --prefer-dist --no-interaction --no-progress --no-ansi

            - name: Execute 7 tests
              run: make phpcs
