name: release

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  coverage: none
                  ini-values: phar.readonly=0

            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Determine version name
              id: get-version
              run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

            - name: Update application version
              run: sed -i 's/Varnish Plus CLI/Varnish Plus CLI ${{ steps.get-version.outputs.version }}/g' bin/varnish-plus-cli.php && cat bin/varnish-plus-cli.php

            - name: Build PHP 7.4 phar with makefile
              run: make dist

            - name: Build PHP 8.0 phar with makefile
              run: make dist-php8

            - name: Check if we can run the phar
              run: |
                - ./dist/varnish-plus-cli.phar --version
                - ./dist/varnish-plus-cli.8.0.phar --version

            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  # This token is provided by GitHub Actions.
                  # You DO NOT need to create your own token.
                  token: ${{ secrets.GITHUB_TOKEN }}
                  name: ${{ steps.get-version.outputs.version }}
                  tag: ${{ steps.get-version.outputs.version }}
                  body: 'Stable release.'
                  artifacts: ./dist/varnish-plus-cli.phar, ./dist/varnish-plus-cli.8.0.phar
                  artifactContentType: application/x-php
