name: release

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code into the workspace
              uses: actions/checkout@v3
            - name: Setup PHP 8.2
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"
                  tools: humbug/box:^4.5
            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Install libraries via Composer
              run: composer update --prefer-dist --no-interaction --no-dev
            - name: Determine version name
              id: get-version
              run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
            - name: Update application version
              run: sed -i 's/Varnish Plus CLI/Varnish Plus CLI ${{ steps.get-version.outputs.version }}/g' bin/varnish-plus-cli.php && cat bin/varnish-plus-cli.php
            - name: Run Box
              run: box --verbose
            - name: Check if we can run the phar
              run: |
                ./dist/varnish-plus-cli.phar --version
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  # This token is provided by GitHub Actions.
                  # You DO NOT need to create your own token.
                  token: ${{ secrets.GITHUB_TOKEN }}
                  name: ${{ steps.get-version.outputs.version }}
                  tag: ${{ steps.get-version.outputs.version }}
                  body: 'Stable release.'
                  artifacts: ./dist/varnish-plus-cli.phar
                  artifactContentType: application/x-php
